### ISSUE TITLE
Adding "www" to URL results in security errors

### ISSUE THREAD

**Issue by coreyjkelly** [StatsBen/ubc-aviary#3]
Along with an overly dire warning:

`This server could not prove that it is www.ubc-aviary.com; its security certificate is from firebaseapp.com. This may be caused by a misconfiguration or an attacker intercepting your connection.`

**Comment by StatsBen** [comment]
Currently attempting to solve this issue by redirecting traffic from the `www` subdomain to the primary domain in Firebase, we'll find out if it worked in a few hours when the changes propagate through and the redirect takes effect.

**Comment by StatsBen** [comment]
Adding that redirect appears to work for me :)
