### ISSUE TITLE
Obfuscate Email Addresses

### ISSUE THREAD

**Issue by coreyjkelly** [StatsBen/ubc-aviary#4]
We should do one of the following to reduce spam received by @ubc-aviary.com emails:

1. Use text obfuscation: address[AT]ubc-aviary[DOT]com
2. Use images containing the email text
3. Use a "contact us" form

Option 1 is easiest, but won't be immune to more clever email scrapers. Option 2 is a bit better, but is annoying for mobile users who need to manually type the address into another app. Option 3 is best, but isn't currently possible because Firebase only supports static assets (no PHP forms).

Ideas?

**Comment by StatsBen** [comment]
I've temporarily resolved this issue by enclosing the @ and . symbols in `<code>` tags - this should prevent the addresses from bot-reading, but if the issue persists we can try something more stubborn!

I'll leave the issue open for now since this is only really a half-solution.

**Comment by coreyjkelly** [comment]
I'm going to add some additional motivation for Option 3: many people seem to choose an email address randomly when they contact us. With a contact form, we could have a dropdown menu like: 

"What do you need help with?"
- I want to take a lesson, or ask a question about lessons
- I want to host a private event at The Aviary
- I want to volunteer at The Aviary 
- Something else

I think the easiest way to accomplish this is with a **mailto** link, which will let us auto-populate the subject and body. Especially handy for bookings, where we can put questions we always need to ask directly in the body:

```
Group Requesting Booking: 
Number of Participants: 
Possible Dates/Times:
etc...
```

This would also let us further obfuscate the email addresses if we need to, since the user will never need to manually type it.

I wouldn't mind taking this on, but might not have time for a while.

**Comment by StatsBen** [comment]
Roger that, Corey! I can see how that would be an issue. I'll try to make some time later this week or next.

**Comment by coreyjkelly** [comment]
I'll assign myself if I get to it before then. Certainly not urgent, but would save a bit of time managing email inboxes!

**Comment by StatsBen** [comment]
I've just implemented a first draft of a solution to this issue, the updates are here in the repo, but haven't been published to the site yet. When you get a chance (no rush at all), have a look at the new buttons and the stubbed out subjects and email bodies - feel free to add or edit anything you think would make 'em better and we can make it live!

**Comment by coreyjkelly** [comment]
Made some minor edits. If it all looks good to you, it can go live!

**Comment by StatsBen** [comment]
Looks good to me. Released! I'll leave the issue open for a few weeks, and after that I'll check in and see if this has helped or if we'd like to loop back and keep iterating :)
